-   id: pylint-reenable
    name: Strip unnecessary `pylint disable`s
    description: Automatically remove unnecessary `pylint disable` comments
    entry: pylint-reenable
    language: python
    types: [python]
